// The barrel the Destination Directory opens with: `index.ts`, re-exporting
// every mirrored module. Precheck reports the clashes that would make it
// ambiguous.
import { BARREL_FILE_NAME, GENERATED_HEADER } from './consts.js';
import type { Module } from './module.js';
import { Specifier } from './specifier.js';

export class Barrel {
  /**
   * The generated barrel's text: the `@generated` header, then an
   * `export * from` per scanned module that exports something, sorted by path.
   * A declaration file gets `export type * from`, naming the module it
   * describes, since it has no runtime module of its own.
   *
   * ```ts
   * // scanned: schemas/user.ts, schemas/nested/order.ts, schemas/types.d.ts,
   * //          schemas/setup.ts (exports nothing)
   * // @generated by @pvl/schema-compiler. Do not edit: run `pvl compile` to regenerate.
   * export * from './schemas/nested/order.js';
   * export type * from './schemas/types.js';
   * export * from './schemas/user.js';
   * ```
   *
   * A module that exports nothing is left out, since `export *` of it would
   * fail to typecheck.
   */
  public static renderBarrelFile(scannedModules: ReadonlyArray<Module>): string {
    const reExportLines = scannedModules
      .filter((scannedModule) => scannedModule.hasExport())
      .map(({ relative }) => relative.path)
      .sort()
      .map((relativePath) => {
        const specifier = new Specifier(relativePath);
        return `${specifier.isDeclarationFile() ? 'export type *' : 'export *'} from '${specifier.toBarrel().value}';`;
      });
    return `${[GENERATED_HEADER, ...reExportLines].join('\n')}\n`;
  }

  /**
   * Whether `<rootDir>/index.ts` is itself scanned. It is then mirrored like any
   * other file and replaces the generated barrel, which also skips the barrel's
   * DUPLICATE_EXPORT check.
   *
   * ```ts
   * Barrel.hasScannedBarrel([<schemas/user.ts>])             // false: the barrel is generated
   * Barrel.hasScannedBarrel([<index.ts>, <schemas/user.ts>]) // true
   * ```
   */
  public static hasScannedBarrel(scannedModules: ReadonlyArray<Module>): boolean {
    return scannedModules.some(({ relative }) => relative.path === BARREL_FILE_NAME);
  }
}
