// Every constant the compiler shares: the config file and setting defaults,
// each diagnostic code's severity, the Destination Directory's layout, and the
// text every generated module shares.
import {
  SCHEMA_FACTORY,
  SEVERITY,
  type DiagnosticCode,
  type SchemaFactory,
  type Severity,
} from './enums.js';

/** The file name the compiler looks for in the working directory. */
export const CONFIG_FILE_NAME = 'pvlconfig.json' as const;

/** The `include` setting's default. */
export const DEFAULT_INCLUDE = ['src/schemas/**/*.ts'] as const;

/** The `rootDir` setting's default. */
export const DEFAULT_ROOT_DIR = 'src' as const;

/** The `withTypes` setting's default. */
export const DEFAULT_WITH_TYPES = true as const;

/** The `watch` setting's default. */
export const DEFAULT_WATCH = false as const;

/**
 * The severity each code is raised with, before `strict` promotes warnings.
 *
 * @example
 * ```ts
 * import { DIAGNOSTIC_SEVERITY } from '@pvl/schema-compiler';
 *
 * DIAGNOSTIC_SEVERITY.FILE_EXPORTS_NOTHING; // 'WARNING'
 * ```
 */
export const DIAGNOSTIC_SEVERITY = {
  NO_CONFIG: SEVERITY.ERROR,
  CONFIG_UNREADABLE: SEVERITY.ERROR,
  INVALID_CONFIG: SEVERITY.ERROR,
  NO_INPUT_FILES: SEVERITY.ERROR,
  DESTINATION_UNWRITABLE: SEVERITY.ERROR,
  DESTINATION_NOT_EMPTY: SEVERITY.ERROR,
  DESTINATION_INSIDE_INCLUDE: SEVERITY.ERROR,
  DUPLICATE_EXPORT: SEVERITY.ERROR,
  TSCONFIG_UNREADABLE: SEVERITY.ERROR,
  PARSE_FAILED: SEVERITY.ERROR,
  FILE_OUTSIDE_ROOT_DIR: SEVERITY.ERROR,
  DEFAULT_EXPORT: SEVERITY.ERROR,
  FILE_EXPORTS_NOTHING: SEVERITY.WARNING,
  SIDE_EFFECT_COPIED: SEVERITY.WARNING,
  COMPILE_ARGUMENT_UNRESOLVABLE: SEVERITY.ERROR,
  COMPILE_ARGUMENT_NOT_COMPOSITE: SEVERITY.ERROR,
  COMPILE_RESULT_MODIFIED: SEVERITY.ERROR,
  UNSUPPORTED_SCHEMA: SEVERITY.ERROR,
  INVALID_ARGUMENTS: SEVERITY.ERROR,
} as const satisfies Record<DiagnosticCode, Severity>;

/** Where the Destination Directory goes, relative to the base directory, when `destination` is unset. */
export const DEFAULT_DESTINATION_DIRECTORY = '.pvl' as const;

/** The file that marks a Destination Directory as written by the compiler, so a later run may replace it. */
export const GENERATED_MARKER_FILE_NAME = '.pvl-generated' as const;

/** The marker file's contents. */
export const GENERATED_MARKER_TEXT =
  'Written by @pvl/schema-compiler. `pvl compile` replaces this whole directory.\n' as const;

/** Appended to the destination's name for the sibling directory a run writes into before it moves into place. */
export const TEMPORARY_DESTINATION_SUFFIX = '.pvl-tmp' as const;

/** Appended to the destination's name for the sibling directory the previous output waits in until the new one is in place. */
export const BACKUP_DESTINATION_SUFFIX = '.pvl-old' as const;

/** The name of the `.gitignore` the default destination gets. */
export const GITIGNORE_FILE_NAME = '.gitignore' as const;

/** The default destination's `.gitignore`, which keeps the whole directory out of version control. */
export const DEFAULT_DESTINATION_GITIGNORE_TEXT = '*\n' as const;

/** The barrel's file name, at the root of the Destination Directory. */
export const BARREL_FILE_NAME = 'index.ts' as const;

/** The first line of every file the compiler writes. */
export const GENERATED_HEADER =
  '// @generated by @pvl/schema-compiler. Do not edit: run `pvl compile` to regenerate.' as const;

/** The import a module holding a Compiled Schema gets, aliasing `@pvl/schema`'s exports so they can't clash with the module's own. */
export const COMPILED_SCHEMA_IMPORT =
  "import { Schema as PvlSchema, type Issue as PvlIssue, type Result as PvlResult } from '@pvl/schema';" as const;

/** The Issue path of a check on a Compiled Schema's root value: `undefined` at the root, as `Issue` itself makes it. */
export const ROOT_ISSUE_PATH = 'path.length > 0 ? path : undefined' as const;

/** The factories of the Schemas `pvl.compile()` may wrap: an object, an array or a union. */
export const COMPOSITE_FACTORIES: ReadonlySet<SchemaFactory> = new Set([
  SCHEMA_FACTORY.OBJECT,
  SCHEMA_FACTORY.ARRAY,
  SCHEMA_FACTORY.UNION,
]);
