// The barrel the Destination Directory opens with: `index.ts`, re-exporting
// every mirrored module. Precheck reports the clashes that would make it
// ambiguous.
import { GENERATED_HEADER } from '../consts.js';
import { Precheck } from './precheck.js';
import type { ScannedModule } from './scannedModule.js';
import { isDeclarationFile, toBarrelModuleSpecifier } from './utils.js';

/**
 * The generated barrel's text: the `@generated` header, then an
 * `export * from` per scanned module that exports something, sorted by path.
 * A declaration file gets `export type * from`, naming the module it
 * describes, since it has no runtime module of its own.
 *
 * ```ts
 * // scanned: schemas/user.ts, schemas/nested/order.ts, schemas/types.d.ts,
 * //          schemas/setup.ts (exports nothing)
 * // @generated by @pvl/schema-compiler. Do not edit: run `pvl compile` to regenerate.
 * export * from './schemas/nested/order.js';
 * export type * from './schemas/types.js';
 * export * from './schemas/user.js';
 * ```
 *
 * A module that exports nothing is left out, since `export *` of it would
 * fail to typecheck.
 */
export const renderBarrel = (scannedModules: ReadonlyArray<ScannedModule>): string => {
  const reExportLines = scannedModules
    .filter(({ sourceFile }) => Precheck.hasExport(sourceFile.getStatements()))
    .map(({ relative }) => relative.path)
    .sort()
    .map(
      (relativePath) =>
        `${isDeclarationFile(relativePath) ? 'export type *' : 'export *'} from '${toBarrelModuleSpecifier(relativePath)}';`,
    );
  return `${[GENERATED_HEADER, ...reExportLines].join('\n')}\n`;
};
