// The barrel the Destination Directory opens with: `index.ts`, re-exporting
// every mirrored module, and the clashes that would make it ambiguous.
import type { Node } from 'ts-morph';
import { DIAGNOSTIC_CODE } from '../../diagnostics/consts.js';
import { createDiagnostic } from '../../diagnostics/createDiagnostic.js';
import type { Diagnostic } from '../../diagnostics/diagnostic.js';
import { GENERATED_HEADER } from '../consts.js';
import { Precheck } from './precheck.js';
import type { ScannedModule } from './scannedModule.js';
import { toBarrelModuleSpecifier } from './utils.js';

/** Names `export *` never re-exports, so they can't clash in the barrel: DEFAULT_EXPORT reports them instead. */
const NAMES_SKIPPED_BY_EXPORT_STAR: ReadonlySet<string> = new Set(['default', 'export=']);

// The first module, by path, to export a name, with what that name is bound to.
type FirstExport = {
  /** Relative to the Root Directory. */
  relativePath: string;
  declarations: ReadonlyArray<Node>;
};

// Whether two exports of one name are bound to the same declarations, as a
// re-export of a binding is; ESM then treats `export *` of both as one export.
//
//   // user.ts: export const user = …;    forward.ts: export { user } from './user.js';
//   → same: both lead to user.ts's `user`
//   // a.ts: export const user = …;       b.ts: export const user = …;
//   → different
const isSameBinding = (
  firstDeclarations: ReadonlyArray<Node>,
  laterDeclarations: ReadonlyArray<Node>,
): boolean => {
  return (
    firstDeclarations.length === laterDeclarations.length &&
    laterDeclarations.every((declaration) => firstDeclarations.includes(declaration))
  );
};

/**
 * A DUPLICATE_EXPORT error for each name a scanned module exports that an
 * earlier one, by path, already exports bound to something else: the
 * barrel's `export *` of both would be ambiguous, so neither would be
 * exported. Re-exports are followed to their declarations, so re-exporting
 * a binding under the name it already has isn't a clash.
 *
 * ```ts
 * // src/schemas/a.ts: export const user = pvl.object({ … });
 * // src/schemas/b.ts: export const user = pvl.object({ … });   // DUPLICATE_EXPORT on b.ts
 * // src/schemas/c.ts: export { user } from './a.js';           // fine: the same binding
 * ```
 */
export const findDuplicateExports = (
  scannedModules: ReadonlyArray<ScannedModule>,
): Diagnostic[] => {
  const firstExportByExportedName = new Map<string, FirstExport>();
  const duplicateExportDiagnostics: Diagnostic[] = [];
  for (const { path, relativePath, sourceFile } of [...scannedModules].sort((first, second) =>
    first.relativePath < second.relativePath ? -1 : 1,
  )) {
    for (const [exportedName, declarations] of sourceFile.getExportedDeclarations()) {
      const firstExport = firstExportByExportedName.get(exportedName);
      if (NAMES_SKIPPED_BY_EXPORT_STAR.has(exportedName)) {
        continue;
      }
      if (firstExport === undefined) {
        firstExportByExportedName.set(exportedName, { relativePath, declarations });
      } else if (!isSameBinding(firstExport.declarations, declarations)) {
        duplicateExportDiagnostics.push(
          createDiagnostic({
            code: DIAGNOSTIC_CODE.DUPLICATE_EXPORT,
            message: `\`${exportedName}\` is also exported by ${firstExport.relativePath}, bound to something else, so the barrel can't re-export both. Rename one of them.`,
            file: path,
          }),
        );
      }
    }
  }
  return duplicateExportDiagnostics;
};

/**
 * The generated barrel's text: the `@generated` header, then an
 * `export * from` per scanned module that exports something, sorted by path.
 *
 * ```ts
 * // scanned: schemas/user.ts, schemas/nested/order.ts, schemas/setup.ts (exports nothing)
 * // @generated by @pvl/schema-compiler. Do not edit: run `pvl compile` to regenerate.
 * export * from './schemas/nested/order.js';
 * export * from './schemas/user.js';
 * ```
 *
 * A module that exports nothing is left out, since `export *` of it would
 * fail to typecheck.
 */
export const renderBarrel = (scannedModules: ReadonlyArray<ScannedModule>): string => {
  const reExportLines = scannedModules
    .filter(({ sourceFile }) => Precheck.hasExport(sourceFile.getStatements()))
    .map(({ relativePath }) => relativePath)
    .sort()
    .map((relativePath) => `export * from '${toBarrelModuleSpecifier(relativePath)}';`);
  return `${[GENERATED_HEADER, ...reExportLines].join('\n')}\n`;
};
