// Which severity each diagnostic code is raised with.
import { SEVERITY, type DiagnosticCode, type Severity } from './enums.js';

/**
 * The severity each code is raised with, before `strict` promotes warnings.
 *
 * @example
 * ```ts
 * import { DIAGNOSTIC_SEVERITY } from '@pvl/schema-compiler';
 *
 * DIAGNOSTIC_SEVERITY.FILE_EXPORTS_NOTHING; // 'WARNING'
 * ```
 */
export const DIAGNOSTIC_SEVERITY = {
  NO_CONFIG: SEVERITY.ERROR,
  CONFIG_UNREADABLE: SEVERITY.ERROR,
  INVALID_CONFIG: SEVERITY.ERROR,
  NO_INPUT_FILES: SEVERITY.ERROR,
  DESTINATION_UNWRITABLE: SEVERITY.ERROR,
  DESTINATION_NOT_EMPTY: SEVERITY.ERROR,
  DESTINATION_INSIDE_INCLUDE: SEVERITY.ERROR,
  DUPLICATE_EXPORT: SEVERITY.ERROR,
  TSCONFIG_UNREADABLE: SEVERITY.ERROR,
  PARSE_FAILED: SEVERITY.ERROR,
  FILE_OUTSIDE_ROOT_DIR: SEVERITY.ERROR,
  DEFAULT_EXPORT: SEVERITY.ERROR,
  FILE_EXPORTS_NOTHING: SEVERITY.WARNING,
  SIDE_EFFECT_COPIED: SEVERITY.WARNING,
  INVALID_ARGUMENTS: SEVERITY.ERROR,
} as const satisfies Record<DiagnosticCode, Severity>;
