// Where the Destination Directory goes by default, what marks it as the
// compiler's own, and the header every file in it opens with.

/** Where the Destination Directory goes, relative to the base directory, when `destination` is unset. */
export const DEFAULT_DESTINATION_DIRECTORY = '.pvl' as const;

/** The file that marks a Destination Directory as written by the compiler, so a later run may replace it. */
export const GENERATED_MARKER_FILE_NAME = '.pvl-generated' as const;

/** The marker file's contents. */
export const GENERATED_MARKER_TEXT =
  'Written by @pvl/schema-compiler. `pvl compile` replaces this whole directory.\n' as const;

/** The name of the `.gitignore` the default destination gets. */
export const GITIGNORE_FILE_NAME = '.gitignore' as const;

/** The default destination's `.gitignore`, which keeps the whole directory out of version control. */
export const DEFAULT_DESTINATION_GITIGNORE_TEXT = '*\n' as const;

/** The barrel's file name, at the root of the Destination Directory. */
export const BARREL_FILE_NAME = 'index.ts' as const;

/** The first line of every file the compiler writes. */
export const GENERATED_HEADER =
  '// @generated by @pvl/schema-compiler. Do not edit: run `pvl compile` to regenerate.' as const;
