import { chmod, mkdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import type { Schema } from '@pvl/schema';
import { describe, expect, it } from 'vitest';
import { compile, DIAGNOSTIC_CODE, SEVERITY } from '../src/index.js';
import { SCHEMA_FILE } from './consts.js';
import {
  configJson,
  createFixture,
  diagnosticCodes,
  expectFailure,
  linkSchemaPackage,
  listFixtureFiles,
  readFixtureFile,
} from './helpers.js';

// What the runtime test reads off a mirrored module, the barrel and the source they mirror.
type OrderModule = { order: Pick<Schema<unknown>, 'validate'> };

// A scanned file importing another, so the runtime test crosses a module boundary.
const ORDER_FILE = [
  "import { pvl } from '@pvl/schema';",
  "import { user } from './user.js';",
  '',
  'export const order = pvl.object({ customer: user, total: pvl.number() });',
  '',
].join('\n');

describe('compile(): writing the Destination Directory', () => {
  it('mirrors each scanned file at its path relative to rootDir, under the generated header, with a barrel', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/nested/order.ts': [
        "import { pvl } from '@pvl/schema';",
        "import { user } from '../user.js';",
        '',
        'export const order = pvl.object({ customer: user });',
        '',
      ].join('\n'),
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(payload.written).toBe(true);
    expect(payload.destination).toBe(join(root, '.pvl'));
    expect(await listFixtureFiles(root, '.pvl')).toEqual([
      '.gitignore',
      '.pvl-generated',
      'index.ts',
      'schemas/nested/order.ts',
      'schemas/user.ts',
    ]);
    expect(await readFixtureFile(root, '.pvl/.gitignore')).toBe('*\n');
    expect(await readFixtureFile(root, '.pvl/schemas/nested/order.ts')).toMatchInlineSnapshot(`
      "// @generated by @pvl/schema-compiler. Do not edit: run \`pvl compile\` to regenerate.
      import { pvl } from '@pvl/schema';
      import { user } from '../user.js';

      export const order = pvl.object({ customer: user });
      "
    `);
    expect(await readFixtureFile(root, '.pvl/index.ts')).toMatchInlineSnapshot(`
      "// @generated by @pvl/schema-compiler. Do not edit: run \`pvl compile\` to regenerate.
      export * from './schemas/nested/order.js';
      export * from './schemas/user.js';
      "
    `);
  });

  it('writes mirrored modules and a barrel that validate as their source does', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/order.ts': ORDER_FILE,
    });
    await linkSchemaPackage(root);

    const payload = await compile({ cwd: root });
    const source = (await import(join(root, 'src/schemas/order.ts'))) as OrderModule;
    const mirrored = (await import(join(root, '.pvl/schemas/order.ts'))) as OrderModule;
    const barrel = (await import(join(root, '.pvl/index.ts'))) as OrderModule;

    expect(payload.diagnostics).toEqual([]);
    for (const value of [
      { customer: { name: 'Ada' }, total: 3 },
      { customer: {}, total: 'x' },
    ]) {
      expect(mirrored.order.validate(value)).toEqual(source.order.validate(value));
      expect(barrel.order.validate(value)).toEqual(source.order.validate(value));
    }
  });

  it('rewrites every module specifier naming an unscanned file to reach the original', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'generated' }),
      'src/lib/helpers.ts':
        'export const nonEmpty = <T>(schema: T): T => schema;\nexport const trim = 1;\n',
      'src/schemas/user.ts': [
        "import { pvl } from '@pvl/schema';",
        "import { nonEmpty } from '../lib/helpers.js';",
        "import '../lib/setup';",
        "export { trim } from '../lib/helpers.js';",
        "import fs = require('../lib/fs.js');",
        "export type Options = import('../lib/types.js').Options;",
        '',
        "export const loadHeavy = () => import('../lib/heavy.js');",
        'export const loadLocale = (lang: string) => import(`../lib/${lang}.js`);',
        'export const user = pvl.object({ name: nonEmpty(pvl.string()) });',
        '',
      ].join('\n'),
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await readFixtureFile(root, 'generated/schemas/user.ts')).toMatchInlineSnapshot(`
      "// @generated by @pvl/schema-compiler. Do not edit: run \`pvl compile\` to regenerate.
      import { pvl } from '@pvl/schema';
      import { nonEmpty } from '../../src/lib/helpers.js';
      import '../../src/lib/setup';
      export { trim } from '../../src/lib/helpers.js';
      import fs = require('../../src/lib/fs.js');
      export type Options = import('../../src/lib/types.js').Options;

      export const loadHeavy = () => import('../../src/lib/heavy.js');
      export const loadLocale = (lang: string) => import(\`../lib/\${lang}.js\`);
      export const user = pvl.object({ name: nonEmpty(pvl.string()) });
      "
    `);
  });

  it('rewrites an alias import to a relative path, through the mirror for a scanned file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'tsconfig.json': JSON.stringify({ compilerOptions: { paths: { '@/*': ['./src/*'] } } }),
      'src/lib/helpers.ts': 'export const label = 1;\n',
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/order.ts': [
        "import { pvl } from '@pvl/schema';",
        "import { label } from '@/lib/helpers';",
        "import { user } from '@/schemas/user.js';",
        "import { missing } from '@/lib/missing';",
        '',
        'export const order = pvl.object({ customer: user, label: pvl.literal(label), missing });',
        '',
      ].join('\n'),
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await readFixtureFile(root, '.pvl/schemas/order.ts')).toMatchInlineSnapshot(`
      "// @generated by @pvl/schema-compiler. Do not edit: run \`pvl compile\` to regenerate.
      import { pvl } from '@pvl/schema';
      import { label } from '../../src/lib/helpers';
      import { user } from './user.js';
      import { missing } from '@/lib/missing';

      export const order = pvl.object({ customer: user, label: pvl.literal(label), missing });
      "
    `);
  });

  it('mirrors a scanned <rootDir>/index.ts as the barrel, generating none and allowing its clashes', async () => {
    const index = "export { user } from './schemas/user.js';\n";
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['src/**/*.ts'] }),
      'src/index.ts': index,
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/other-user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await readFixtureFile(root, '.pvl/index.ts')).toBe(
      `// @generated by @pvl/schema-compiler. Do not edit: run \`pvl compile\` to regenerate.\n${index}`,
    );
  });

  it('keeps an import cycle and a namespace import between scanned files as written', async () => {
    const a = "import * as b from './b.js';\nexport const a = () => b.b;\n";
    const b = "import { a } from './a.js';\nexport const b = () => a;\n";
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/a.ts': a,
      'src/schemas/b.ts': b,
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await readFixtureFile(root, '.pvl/schemas/a.ts')).toContain(a);
    expect(await readFixtureFile(root, '.pvl/schemas/b.ts')).toContain(b);
  });

  it('mirrors relative to a configured rootDir, and adds no .gitignore to a configured destination', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({
        include: ['app/models/*.ts'],
        rootDir: 'app',
        destination: 'compiled',
      }),
      'app/models/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await listFixtureFiles(root, 'compiled')).toEqual([
      '.pvl-generated',
      'index.ts',
      'models/user.ts',
    ]);
  });

  it('writes byte-identical output when run again on unchanged input', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/order.ts': ORDER_FILE,
    });

    await compile({ cwd: root });
    const first = await readFixtureFile(root, '.pvl/schemas/order.ts');
    const firstBarrel = await readFixtureFile(root, '.pvl/index.ts');
    await compile({ cwd: root });

    expect(await readFixtureFile(root, '.pvl/schemas/order.ts')).toBe(first);
    expect(await readFixtureFile(root, '.pvl/index.ts')).toBe(firstBarrel);
  });

  it('replaces a Destination Directory it wrote before, dropping the mirror of a removed file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/order.ts': ORDER_FILE,
    });
    await compile({ cwd: root });
    await rm(join(root, 'src/schemas/order.ts'));

    const payload = await compile({ cwd: root });

    expect(payload.written).toBe(true);
    expect(await listFixtureFiles(root, '.pvl')).toEqual([
      '.gitignore',
      '.pvl-generated',
      'index.ts',
      'schemas/user.ts',
    ]);
  });

  it('re-exports a declaration file from the barrel as types only', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/types.d.ts': 'export type UserId = string;\n',
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await readFixtureFile(root, '.pvl/index.ts')).toMatchInlineSnapshot(`
      "// @generated by @pvl/schema-compiler. Do not edit: run \`pvl compile\` to regenerate.
      export type * from './schemas/types.js';
      export * from './schemas/user.js';
      "
    `);
  });

  it('keeps a package import that tsconfig paths also map, as in a workspace', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'tsconfig.json': JSON.stringify({
        compilerOptions: { paths: { '@pvl/schema': ['./vendor/schema/index.ts'] } },
      }),
      'vendor/schema/index.ts': 'export const pvl = {};\n',
      'src/schemas/user.ts': SCHEMA_FILE,
    });
    await linkSchemaPackage(root);

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await readFixtureFile(root, '.pvl/schemas/user.ts')).toContain(
      "import { pvl } from '@pvl/schema';",
    );
  });

  it('never scans the directories a failed run left beside the destination', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['**/*.ts'], rootDir: '.', destination: 'gen' }),
      'schemas/user.ts': SCHEMA_FILE,
      'gen.pvl-tmp/schemas/user.ts': SCHEMA_FILE,
      'gen.pvl-old/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(diagnosticCodes(payload)).toEqual([DIAGNOSTIC_CODE.DESTINATION_INSIDE_INCLUDE]);
  });

  it('replaces the destination over the directories a failed run left beside it', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'gen' }),
      'src/schemas/user.ts': SCHEMA_FILE,
      'gen/.pvl-generated': '',
      'gen/stale.ts': 'export const stale = 1;\n',
      'gen.pvl-tmp/half-written.ts': '',
      'gen.pvl-old/.pvl-generated': '',
      'gen.pvl-old/older.ts': 'export const older = 1;\n',
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await listFixtureFiles(root, 'gen')).toEqual([
      '.pvl-generated',
      'index.ts',
      'schemas/user.ts',
    ]);
    expect(await listFixtureFiles(root, 'gen.pvl-tmp')).toBe(undefined);
    expect(await listFixtureFiles(root, 'gen.pvl-old')).toBe(undefined);
  });

  it('writes into an existing empty directory', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'generated' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });
    await mkdir(join(root, 'generated'));

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await listFixtureFiles(root, 'generated')).toEqual([
      '.pvl-generated',
      'index.ts',
      'schemas/user.ts',
    ]);
  });
});

describe('compile(): settings', () => {
  it('applies the defaults when the config sets nothing', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(payload.settings).toEqual({
      include: ['src/schemas/**/*.ts'],
      rootDir: 'src',
      destination: undefined,
      withTypes: true,
      watch: false,
    });
  });

  it('reads every setting from the config file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({
        $schema: './node_modules/@pvl/schema-compiler/dist/json-schema.json',
        include: ['schemas/*.ts'],
        rootDir: 'schemas',
        destination: 'out',
        withTypes: false,
        watch: true,
      }),
      'schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(payload.settings).toEqual({
      include: ['schemas/*.ts'],
      rootDir: 'schemas',
      destination: 'out',
      withTypes: false,
      watch: true,
    });
  });

  it('lets an override win over the config file, setting by setting', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({
        include: ['schemas/*.ts'],
        rootDir: '.',
        destination: 'from-config',
        withTypes: false,
      }),
      'schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({
      cwd: root,
      overrides: { rootDir: 'schemas', destination: 'from-override', withTypes: true },
    });

    expect(payload.settings).toEqual({
      include: ['schemas/*.ts'],
      rootDir: 'schemas',
      destination: 'from-override',
      withTypes: true,
      watch: false,
    });
    expect(await readFixtureFile(root, 'from-override/user.ts')).toContain('@generated');
    expect(await listFixtureFiles(root, 'from-config')).toBe(undefined);
  });

  it('runs with no config file when overrides are given, resolving paths from the working directory', async () => {
    const root = await createFixture({ 'src/schemas/user.ts': SCHEMA_FILE });

    const payload = await compile({ cwd: root, overrides: { destination: 'out' } });

    expect(payload.diagnostics).toEqual([]);
    expect(payload.destination).toBe(join(root, 'out'));
    expect(await readFixtureFile(root, 'out/schemas/user.ts')).toContain('@generated');
  });

  it("resolves relative paths from the config file's directory, wherever it is run from", async () => {
    const files = {
      'apps/web/pvlconfig.json': configJson({ include: ['src/schemas/*.ts'] }),
      'apps/web/src/schemas/user.ts': SCHEMA_FILE,
    };
    const fromRepoRoot = await createFixture(files);
    const fromApp = await createFixture(files);

    const rootPayload = await compile({
      cwd: fromRepoRoot,
      configPath: 'apps/web/pvlconfig.json',
    });
    const appPayload = await compile({ cwd: join(fromApp, 'apps/web') });

    expect(rootPayload.diagnostics).toEqual([]);
    expect(appPayload.diagnostics).toEqual([]);
    expect(rootPayload.destination).toBe(join(fromRepoRoot, 'apps/web/.pvl'));
    expect(appPayload.destination).toBe(join(fromApp, 'apps/web/.pvl'));
    expect(await readFixtureFile(fromRepoRoot, 'apps/web/.pvl/schemas/user.ts')).toBe(
      await readFixtureFile(fromApp, 'apps/web/.pvl/schemas/user.ts'),
    );
  });

  it('never scans node_modules', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['**/*.ts'], rootDir: '.' }),
      'src/user.ts': SCHEMA_FILE,
      'node_modules/dep/index.ts': 'console.log("side effect");\n',
    });

    const payload = await compile({ cwd: root });

    // `index.ts` exports nothing, so scanning it would have warned.
    expect(payload.diagnostics).toEqual([]);
  });
});

describe('compile(): diagnostics', () => {
  it('NO_CONFIG: no config file and no overrides', async () => {
    const root = await createFixture({ 'src/schemas/user.ts': SCHEMA_FILE });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [{ code: DIAGNOSTIC_CODE.NO_CONFIG }]);
  });

  it('CONFIG_UNREADABLE: an explicit config path that does not exist', async () => {
    const root = await createFixture({ 'src/schemas/user.ts': SCHEMA_FILE });

    const payload = await compile({ cwd: root, configPath: 'missing.json' });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.CONFIG_UNREADABLE, file: join(root, 'missing.json') },
    ]);
  });

  it('CONFIG_UNREADABLE: a config file that is not valid JSON', async () => {
    const root = await createFixture({
      'pvlconfig.json': '{ "destination": ',
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.CONFIG_UNREADABLE, file: join(root, 'pvlconfig.json') },
    ]);
  });

  it('INVALID_CONFIG: one diagnostic per failing setting, naming its path', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: 'src/**/*.ts', rootDir: 1, withTypes: 'yes' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    const file = join(root, 'pvlconfig.json');
    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.INVALID_CONFIG, file },
      { code: DIAGNOSTIC_CODE.INVALID_CONFIG, file },
      { code: DIAGNOSTIC_CODE.INVALID_CONFIG, file },
    ]);
    expect(payload.diagnostics[0]?.message).toContain('include');
    expect(payload.diagnostics[1]?.message).toContain('rootDir');
    expect(payload.diagnostics[2]?.message).toContain('withTypes');
  });

  it('INVALID_CONFIG: an unknown key, so a typo is reported', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destinaton: 'out' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.INVALID_CONFIG, file: join(root, 'pvlconfig.json') },
    ]);
    expect(payload.diagnostics[0]?.message).toContain('destinaton');
    expect(await listFixtureFiles(root, 'out')).toBe(undefined);
  });

  it('INVALID_CONFIG: a config file that is not an object', async () => {
    const root = await createFixture({
      'pvlconfig.json': '[]',
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.INVALID_CONFIG, file: join(root, 'pvlconfig.json') },
    ]);
  });

  it('INVALID_CONFIG: an override of the wrong type, with no file', async () => {
    const root = await createFixture({ 'src/schemas/user.ts': SCHEMA_FILE });

    const payload = await compile({
      cwd: root,
      overrides: { destination: 42 as unknown as string },
    });

    expectFailure(payload, [{ code: DIAGNOSTIC_CODE.INVALID_CONFIG }]);
  });

  it('NO_INPUT_FILES: include matches no file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['schemas/*.ts'] }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [{ code: DIAGNOSTIC_CODE.NO_INPUT_FILES }]);
    expect(await listFixtureFiles(root, '.pvl')).toBe(undefined);
  });

  it('NO_INPUT_FILES: include matches only directories', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['src/*'] }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [{ code: DIAGNOSTIC_CODE.NO_INPUT_FILES }]);
  });

  it('DESTINATION_INSIDE_INCLUDE: include would match a file written into the destination', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['src/**/*.ts'], destination: 'src/compiled' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.DESTINATION_INSIDE_INCLUDE, file: join(root, 'src/compiled') },
    ]);
    expect(await listFixtureFiles(root, 'src/compiled')).toBe(undefined);
  });

  it('DESTINATION_INSIDE_INCLUDE: also outside the base directory', async () => {
    const root = await createFixture({
      'app/pvlconfig.json': configJson({
        include: ['../shared/**/*.ts'],
        rootDir: '../shared',
        destination: '../shared/out',
      }),
      'shared/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: join(root, 'app') });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.DESTINATION_INSIDE_INCLUDE, file: join(root, 'shared/out') },
    ]);
  });

  it('DESTINATION_UNWRITABLE: the destination is an existing file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'out' }),
      'src/schemas/user.ts': SCHEMA_FILE,
      out: 'notes',
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.DESTINATION_UNWRITABLE, file: join(root, 'out') },
    ]);
    expect(await readFixtureFile(root, 'out')).toBe('notes');
  });

  it('DESTINATION_UNWRITABLE: a parent of the destination is a file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'notes.txt/out' }),
      'src/schemas/user.ts': SCHEMA_FILE,
      'notes.txt': '',
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.DESTINATION_UNWRITABLE, file: join(root, 'notes.txt/out') },
    ]);
    expect(await readFixtureFile(root, 'notes.txt')).toBe('');
  });

  it('DESTINATION_UNWRITABLE: the directory the destination would be created in is read-only', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'locked/nested/out' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });
    await mkdir(join(root, 'locked'));
    await chmod(join(root, 'locked'), 0o555);

    try {
      const payload = await compile({ cwd: root });

      expectFailure(payload, [
        { code: DIAGNOSTIC_CODE.DESTINATION_UNWRITABLE, file: join(root, 'locked/nested/out') },
      ]);
      expect(await listFixtureFiles(root, 'locked')).toEqual([]);
    } finally {
      await chmod(join(root, 'locked'), 0o755);
    }
  });

  it('DESTINATION_NOT_EMPTY: the destination holds files the compiler did not write', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'src/app' }),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/app/main.ts': 'start();\n',
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.DESTINATION_NOT_EMPTY, file: join(root, 'src/app') },
    ]);
    expect(await listFixtureFiles(root, 'src/app')).toEqual(['main.ts']);
  });

  it('TSCONFIG_UNREADABLE: the tsconfig is not valid JSON', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'tsconfig.json': '{ "compilerOptions": ',
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.TSCONFIG_UNREADABLE, file: join(root, 'tsconfig.json') },
    ]);
    expect(await listFixtureFiles(root, '.pvl')).toBe(undefined);
  });

  it('TSCONFIG_UNREADABLE: the tsconfig extends a file that does not exist', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'tsconfig.json': JSON.stringify({ extends: './missing.json' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.TSCONFIG_UNREADABLE, file: join(root, 'tsconfig.json') },
    ]);
  });

  it('TSCONFIG_UNREADABLE: the tsconfig exists but may not be read', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'tsconfig.json': '{}',
      'src/schemas/user.ts': SCHEMA_FILE,
    });
    await chmod(join(root, 'tsconfig.json'), 0o000);

    try {
      const payload = await compile({ cwd: root });

      expectFailure(payload, [
        { code: DIAGNOSTIC_CODE.TSCONFIG_UNREADABLE, file: join(root, 'tsconfig.json') },
      ]);
    } finally {
      await chmod(join(root, 'tsconfig.json'), 0o644);
    }
  });

  it('TSCONFIG_UNREADABLE: not raised for a tsconfig whose include matches no file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'tsconfig.json': JSON.stringify({ include: ['app/**/*.ts'] }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
  });

  it('PARSE_FAILED: a scanned file is not valid syntax', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/broken.ts': 'export const = pvl.object({;\n',
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.PARSE_FAILED, file: join(root, 'src/schemas/broken.ts') },
    ]);
    expect(await listFixtureFiles(root, '.pvl')).toBe(undefined);
  });

  it('FILE_OUTSIDE_ROOT_DIR: a scanned file is not under rootDir', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['src/schemas/*.ts', 'lib/*.ts'] }),
      'src/schemas/user.ts': SCHEMA_FILE,
      'lib/helpers.ts': 'export const label = 1;\n',
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.FILE_OUTSIDE_ROOT_DIR, file: join(root, 'lib/helpers.ts') },
    ]);
  });

  it('DEFAULT_EXPORT: every form of default export, one per statement', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/a.ts': "import { pvl } from '@pvl/schema';\nexport default pvl.string();\n",
      'src/schemas/b.ts': 'export default function format(): void {}\n',
      'src/schemas/c.ts': 'const c = 1;\nexport { c as default };\n',
      'src/schemas/d.ts': "export { default } from './legacy.js';\n",
      'src/schemas/e.ts': 'const e = 1;\nexport = e;\n',
    });

    const payload = await compile({ cwd: root });

    expectFailure(
      payload,
      ['a', 'b', 'c', 'd', 'e'].map((name) => ({
        code: DIAGNOSTIC_CODE.DEFAULT_EXPORT,
        file: join(root, `src/schemas/${name}.ts`),
      })),
    );
  });

  it('DEFAULT_EXPORT: not raised for a default re-exported under a name', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/lib/legacy.ts': 'export default 1;\n',
      'src/schemas/a.ts': "export { default as legacy } from '../lib/legacy.js';\n",
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
  });

  it('DUPLICATE_EXPORT: two scanned files export the same name', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/a.ts': SCHEMA_FILE,
      'src/schemas/b.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.DUPLICATE_EXPORT, file: join(root, 'src/schemas/b.ts') },
    ]);
  });

  it('DUPLICATE_EXPORT: not raised when a file re-exports a binding under the name it already has', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/forward.ts': "export { user } from './user.js';\n",
      'src/schemas/reexport.ts': "import { user } from './user.js';\nexport { user };\n",
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
  });

  it('FILE_EXPORTS_NOTHING: a warning that still writes, leaving the file out of the barrel', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/setup.ts': 'const internal = 1;\n',
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toStrictEqual([
      {
        code: DIAGNOSTIC_CODE.FILE_EXPORTS_NOTHING,
        severity: SEVERITY.WARNING,
        message: expect.any(String),
        file: join(root, 'src/schemas/setup.ts'),
      },
    ]);
    expect(payload.written).toBe(true);
    expect(await readFixtureFile(root, '.pvl/schemas/setup.ts')).toContain('const internal = 1;');
    expect(await readFixtureFile(root, '.pvl/index.ts')).not.toContain('setup');
  });

  it('SIDE_EFFECT_COPIED: a warning that still copies the statement and writes', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': `${SCHEMA_FILE}\nif (process.env.DEBUG) {\n  console.log(user);\n}\n`,
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toStrictEqual([
      {
        code: DIAGNOSTIC_CODE.SIDE_EFFECT_COPIED,
        severity: SEVERITY.WARNING,
        message: expect.any(String),
        file: join(root, 'src/schemas/user.ts'),
      },
    ]);
    expect(payload.written).toBe(true);
    expect(await readFixtureFile(root, '.pvl/schemas/user.ts')).toContain('console.log(user);');
  });

  it('SIDE_EFFECT_COPIED: strict turns it into an error that writes nothing', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': `${SCHEMA_FILE}console.log(user);\n`,
    });

    const payload = await compile({ cwd: root, strict: true });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.SIDE_EFFECT_COPIED, file: join(root, 'src/schemas/user.ts') },
    ]);
    expect(await listFixtureFiles(root, '.pvl')).toBe(undefined);
  });

  it('strict: promotes a warning to an error, so the previous output is kept', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/setup.ts': 'const internal = 1;\n',
      '.pvl/.pvl-generated': '',
      '.pvl/index.ts': 'previous output',
    });

    const payload = await compile({ cwd: root, strict: true });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.FILE_EXPORTS_NOTHING, file: join(root, 'src/schemas/setup.ts') },
    ]);
    expect(await readFixtureFile(root, '.pvl/index.ts')).toBe('previous output');
  });

  it('COMPILE_ARGUMENT_UNRESOLVABLE: an argument or a method argument that is not written in the file', async () => {
    const path = 'src/schemas/compiled.ts';
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
      [path]: [
        "import { pvl } from '@pvl/schema';",
        "import { user } from './user.js';",
        '',
        'const makeSchema = () => pvl.object({});',
        'let limit = 3;',
        'export const imported = pvl.compile(user);',
        'export const built = pvl.compile(makeSchema());',
        'export const spread = pvl.compile(pvl.object({ ...user.shape }));',
        'export const variableLimit = pvl.compile(pvl.array(pvl.string()).max(limit));',
        '',
      ].join('\n'),
    });

    const payload = await compile({ cwd: root });

    expectFailure(
      payload,
      Array.from({ length: 4 }, () => ({
        code: DIAGNOSTIC_CODE.COMPILE_ARGUMENT_UNRESOLVABLE,
        file: join(root, path),
      })),
    );
  });

  it('COMPILE_ARGUMENT_NOT_COMPOSITE: pvl.compile() wraps a primitive, a literal or an enum', async () => {
    const path = 'src/schemas/compiled.ts';
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      [path]: [
        "import { pvl } from '@pvl/schema';",
        '',
        'export const name = pvl.compile(pvl.string().min(1));',
        "export const kind = pvl.compile(pvl.literal('user'));",
        "export const role = pvl.compile(pvl.enum(['A', 'B']));",
        '',
      ].join('\n'),
    });

    const payload = await compile({ cwd: root });

    expectFailure(
      payload,
      Array.from({ length: 3 }, () => ({
        code: DIAGNOSTIC_CODE.COMPILE_ARGUMENT_NOT_COMPOSITE,
        file: join(root, path),
      })),
    );
  });

  it('COMPILE_RESULT_MODIFIED: a Modifier chained onto the result, but not validate()', async () => {
    const path = 'src/schemas/compiled.ts';
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      [path]: [
        "import { pvl } from '@pvl/schema';",
        '',
        'export const user = pvl.compile(pvl.object({})).optional();',
        'export const tags = pvl.compile(pvl.array(pvl.string())).min(1);',
        'export const checked = pvl.compile(pvl.object({})).validate({});',
        '',
      ].join('\n'),
    });

    const payload = await compile({ cwd: root });

    expectFailure(
      payload,
      Array.from({ length: 2 }, () => ({
        code: DIAGNOSTIC_CODE.COMPILE_RESULT_MODIFIED,
        file: join(root, path),
      })),
    );
  });

  it('UNSUPPORTED_SCHEMA: what is not compiled yet, one diagnostic per problem', async () => {
    const path = 'src/schemas/compiled.ts';
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      [path]: [
        "import { pvl } from '@pvl/schema';",
        '',
        'export const nested = pvl.compile(pvl.object({ tags: pvl.array(pvl.string()) }));',
        'export const refined = pvl.compile(pvl.array(pvl.number().refine((n) => n > 0)));',
        'export const coerced = pvl.compile(pvl.object({ age: pvl.number().coerce() }));',
        'export const optionalRoot = pvl.compile(pvl.object({}).optional());',
        'export const transformed = pvl.compile(pvl.array(pvl.string()).transform((v) => v.length));',
        'export const union = pvl.compile(pvl.union([pvl.string(), pvl.number()]));',
        "export const twice = pvl.compile(pvl.object({ age: pvl.number().coerce(), name: pvl.string().refine((v) => v !== '') }));",
        '',
      ].join('\n'),
    });

    const payload = await compile({ cwd: root });

    expectFailure(
      payload,
      Array.from({ length: 8 }, () => ({
        code: DIAGNOSTIC_CODE.UNSUPPORTED_SCHEMA,
        file: join(root, path),
      })),
    );
  });

  it('reports every error from one run together', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['src/**/*.ts'], destination: 'src/out' }),
    });

    const payload = await compile({ cwd: root });

    expect(diagnosticCodes(payload)).toEqual([
      DIAGNOSTIC_CODE.DESTINATION_INSIDE_INCLUDE,
      DIAGNOSTIC_CODE.NO_INPUT_FILES,
    ]);
  });

  it('reports every mirror error and warning from one run together', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['src/schemas/*.ts', 'lib/*.ts'] }),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/broken.ts': 'export default = ;\n',
      'src/schemas/duplicate.ts': SCHEMA_FILE,
      'src/schemas/legacy.ts': 'export default 1;\n',
      'src/schemas/setup.ts': 'const internal = 1;\n',
      'lib/helpers.ts': 'export const label = 1;\n',
    });

    const payload = await compile({ cwd: root });

    expect(
      payload.diagnostics.map(({ code, severity, file }) => ({ code, severity, file })),
    ).toStrictEqual([
      {
        code: DIAGNOSTIC_CODE.PARSE_FAILED,
        severity: SEVERITY.ERROR,
        file: join(root, 'src/schemas/broken.ts'),
      },
      {
        code: DIAGNOSTIC_CODE.FILE_OUTSIDE_ROOT_DIR,
        severity: SEVERITY.ERROR,
        file: join(root, 'lib/helpers.ts'),
      },
      {
        code: DIAGNOSTIC_CODE.DEFAULT_EXPORT,
        severity: SEVERITY.ERROR,
        file: join(root, 'src/schemas/legacy.ts'),
      },
      {
        code: DIAGNOSTIC_CODE.DUPLICATE_EXPORT,
        severity: SEVERITY.ERROR,
        file: join(root, 'src/schemas/user.ts'),
      },
      {
        code: DIAGNOSTIC_CODE.FILE_EXPORTS_NOTHING,
        severity: SEVERITY.WARNING,
        file: join(root, 'src/schemas/setup.ts'),
      },
    ]);
    expect(payload.written).toBe(false);
  });
});
