import { join } from 'node:path';
import type { Issue, Result, Schema } from '@pvl/schema';
import fc from 'fast-check';
import { Project, ts } from 'ts-morph';
import { describe, expect, it } from 'vitest';
import { compile, type CompilePayload } from '../src/index.js';
import {
  configJson,
  createFixture,
  linkSchemaPackage,
  readFixtureFile,
  schemaFile,
} from './helpers.js';

describe('compile(): emitting Compiled Schemas', () => {
  it('compiles a flat object to straight-line code in its mirrored module', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': schemaFile(
        'export const user = pvl.compile(pvl.object({ name: pvl.string().min(3) }));',
      ),
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await readFixtureFile(root, '.pvl/schemas/user.ts')).toMatchInlineSnapshot(`
      "// @generated by @pvl/schema-compiler. Do not edit: run \`pvl compile\` to regenerate.
      import { pvl } from '@pvl/schema';
      import { Schema as PvlSchema, type Issue as PvlIssue, type Result as PvlResult } from '@pvl/schema';

      // pvl.compile() on line 3
      class PvlCompiledSchema0 extends PvlSchema<{ name: string }, { name: string }> {
        override _checkType(value: unknown, path: ReadonlyArray<PropertyKey>): PvlResult<unknown> {
          const issues: PvlIssue[] = [];
          if (typeof value !== "object" || value === null || Array.isArray(value)) {
            issues.push({ code: "INVALID_TYPE", message: "Expected object", path: path.length > 0 ? path : undefined });
            return { issues };
          }
          const input = value as Record<string, unknown>;

          // name
          const field0 = input["name"];
          if (typeof field0 !== "string") {
            issues.push({ code: "INVALID_TYPE", message: "Expected string", path: [...path, "name"] });
          } else {
            if (field0.length < 3) {
              issues.push({ code: "TOO_SMALL", message: "String must contain at least 3 character(s)", path: [...path, "name"] });
            }
          }

          if (issues.length > 0) {
            return { issues };
          }
          const output: Record<string, unknown> = {};
          output["name"] = field0;
          return { value: output };
        }
      }

      export const user = new PvlCompiledSchema0();
      "
    `);
  });

  it('compiles a flat array, and a strict object with an optional field, numbering each class', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/lists.ts': schemaFile(
        [
          'export const tags = pvl.compile(pvl.array(pvl.string().optional()).max(3));',
          'export const person = pvl.compile(pvl.object({ age: pvl.number().optional() }).strict());',
        ].join('\n'),
      ),
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(await readFixtureFile(root, '.pvl/schemas/lists.ts')).toMatchInlineSnapshot(`
      "// @generated by @pvl/schema-compiler. Do not edit: run \`pvl compile\` to regenerate.
      import { pvl } from '@pvl/schema';
      import { Schema as PvlSchema, type Issue as PvlIssue, type Result as PvlResult } from '@pvl/schema';

      // pvl.compile() on line 3
      class PvlCompiledSchema0 extends PvlSchema<(string | undefined)[], (string | undefined)[]> {
        override _checkType(value: unknown, path: ReadonlyArray<PropertyKey>): PvlResult<unknown> {
          const issues: PvlIssue[] = [];
          if (!Array.isArray(value)) {
            issues.push({ code: "INVALID_TYPE", message: "Expected array", path: path.length > 0 ? path : undefined });
            return { issues };
          }
          const output: unknown[] = [];
          for (let index = 0; index < value.length; index++) {
            const element: unknown = value[index];
            if (element !== undefined) {
              if (typeof element !== "string") {
                issues.push({ code: "INVALID_TYPE", message: "Expected string", path: [...path, index] });
              }
            }
            output.push(element);
          }
          if (issues.length > 0) {
            return { issues };
          }
          if (value.length > 3) {
            issues.push({ code: "TOO_BIG", message: "Array must contain at most 3 element(s)", path: path.length > 0 ? path : undefined });
          }
          if (issues.length > 0) {
            return { issues };
          }
          return { value: output };
        }
      }

      // pvl.compile() on line 4
      class PvlCompiledSchema1 extends PvlSchema<{ age?: number | undefined }, { age?: number | undefined }> {
        override _checkType(value: unknown, path: ReadonlyArray<PropertyKey>): PvlResult<unknown> {
          const issues: PvlIssue[] = [];
          if (typeof value !== "object" || value === null || Array.isArray(value)) {
            issues.push({ code: "INVALID_TYPE", message: "Expected object", path: path.length > 0 ? path : undefined });
            return { issues };
          }
          const input = value as Record<string, unknown>;

          // age
          const field0 = input["age"];
          if (field0 !== undefined) {
            if (typeof field0 !== "number" || Number.isNaN(field0)) {
              issues.push({ code: "INVALID_TYPE", message: "Expected number", path: [...path, "age"] });
            }
          }

          if (issues.length > 0) {
            return { issues };
          }
          for (const key of Object.keys(input)) {
            if (key !== "age") {
              issues.push({ code: "UNRECOGNIZED_KEY", message: "Unrecognized key \\"" + key + "\\"", path: [...path, key] });
            }
          }
          if (issues.length > 0) {
            return { issues };
          }
          const output: Record<string, unknown> = {};
          if (field0 !== undefined || Object.hasOwn(input, "age")) {
            output["age"] = field0;
          }
          return { value: output };
        }
      }

      export const tags = new PvlCompiledSchema0();
      export const person = new PvlCompiledSchema1();
      "
    `);
  });
});

// Every Schema the differential test compiles, by export name: each feature
// of a flat object or array at least once, alone and combined.
const DIFFERENTIAL_CASES: Readonly<Record<string, string>> = {
  everyPrimitive: [
    'pvl.object({',
    '  name: pvl.string().min(2).max(5),',
    '  code: pvl.string().length(2),',
    '  age: pvl.number().int().min(0).max(120).optional(),',
    '  admin: pvl.boolean().nullable(),',
    '  id: pvl.bigint().min(1n).max(100n),',
    "  kind: pvl.literal('user'),",
    "  role: pvl.enum(['ADMIN', 'USER']),",
    '})',
  ].join('\n'),
  strict: "pvl.object({ name: pvl.string(), role: pvl.enum({ A: 'a', B: 1 }) }).strict()",
  strictWithMessage: "pvl.object({ name: pvl.string() }).strict({ message: 'no extras' })",
  passthrough: 'pvl.object({ name: pvl.string().optional() }).passthrough()',
  passthroughThenStrict: 'pvl.object({ name: pvl.string() }).passthrough().strict()',
  strictThenPassthrough: 'pvl.object({ name: pvl.string() }).strict().passthrough()',
  empty: 'pvl.object({})',
  integerKeys: 'pvl.object({ b: pvl.string(), 1: pvl.number(), 0: pvl.boolean() })',
  duplicateEnumMembers: "pvl.array(pvl.enum(['A', 'A', 'B']))",
  customMessages: [
    'pvl.object({',
    "  name: pvl.string().min(3, { message: 'too short' }).max(4, { message: '' }),",
    "  count: pvl.number().int({ message: 'whole' }).min(-1, { message: 'low' }),",
    "  'e-mail': pvl.string().nullable().optional(),",
    "  ['__proto__']: pvl.string().optional(),",
    '})',
  ].join('\n'),
  literals: [
    'pvl.object({',
    '  one: pvl.literal(1),',
    '  negativeZero: pvl.literal(-0).optional(),',
    '  big: pvl.literal(1n).optional(),',
    '  yes: pvl.literal(true).optional(),',
    '})',
  ].join('\n'),
  constants: 'pvl.object({ name, age: pvl.number().max(MAX) })',
  strings: 'pvl.array(pvl.string().min(1)).min(1).max(3)',
  optionalNumbers: 'pvl.array(pvl.number().optional()).length(2)',
  nullableEnums: "pvl.array(pvl.enum(['A', 'B']).nullable())",
  bigints: 'pvl.array(pvl.literal(1n))',
  arrayMessages: "pvl.array(pvl.boolean()).min(2, { message: '' }).max(3, { message: 'too many' })",
};

// An interpreted object whose fields are Compiled Schemas, so their Issues
// are reported under the parent's path.
const INTERPRETED_PARENT =
  'pvl.object({ inner: pvl.compile(pvl.object({ name: pvl.string() }).strict()), list: pvl.compile(pvl.array(pvl.number()).min(1)) })' as const;

// The scanned file the differential test compiles: every case, exported
// compiled, the interpreted parent, and the constants one case reads.
const DIFFERENTIAL_FILE = schemaFile(
  [
    'const MAX = 9;',
    'const name = pvl.string().min(2);',
    ...Object.entries(DIFFERENTIAL_CASES).map(
      ([exportName, source]) => `export const ${exportName} = pvl.compile(${source});`,
    ),
    `export const interpretedParent = ${INTERPRETED_PARENT};`,
  ].join('\n'),
);

// The keys any case declares, plus one none does, so generated objects hit
// declared, missing and unknown keys alike.
const KEYS = [
  'b',
  '0',
  '1',
  'inner',
  'list',
  'name',
  'code',
  'age',
  'admin',
  'id',
  'kind',
  'role',
  'count',
  'e-mail',
  '__proto__',
  'one',
  'negativeZero',
  'big',
  'yes',
  'extra',
];

// Values near every boundary and member the cases check.
const fieldValue: fc.Arbitrary<unknown> = fc.oneof(
  fc.string({ maxLength: 6 }),
  fc.integer({ min: -3, max: 125 }),
  fc.double(),
  fc.bigInt({ min: -5n, max: 150n }),
  fc.boolean(),
  fc.constantFrom(null, undefined, 'user', 'ADMIN', 'USER', 'a', 'A', 'B', 1, 0, -0, 1n, true),
);

const validatedValue: fc.Arbitrary<unknown> = fc.oneof(
  fc.dictionary(fc.constantFrom(...KEYS), fieldValue),
  fc.record(Object.fromEntries(KEYS.map((key) => [key, fieldValue])), { requiredKeys: [] }),
  fc.array(fieldValue, { maxLength: 4 }),
  fc.anything({ withBigInt: true }),
);

// An object whose `inner` and `list` hit the interpreted parent's compiled
// fields with values near what they accept.
const parentValue: fc.Arbitrary<unknown> = fc.record(
  {
    inner: fc.oneof(fc.dictionary(fc.constantFrom('name', 'extra'), fieldValue), fieldValue),
    list: fc.oneof(fc.array(fieldValue, { maxLength: 3 }), fieldValue),
  },
  { requiredKeys: [] },
);

// A Result as plain data: an Issue's class and an object's key order are
// both part of what is compared, the first by dropping it, the second by
// listing it.
const describeResult = (result: Result<unknown>): unknown => {
  if (result.issues) {
    return {
      issues: result.issues.map(({ code, message, path }: Issue) => ({ code, message, path })),
    };
  }
  const { value } = result;
  return {
    value,
    keys: typeof value === 'object' && value !== null ? Reflect.ownKeys(value) : undefined,
  };
};

type CasesModule = Readonly<Record<string, Pick<Schema<unknown>, 'validate'>>>;

// A fixture holding DIFFERENTIAL_FILE, with `@pvl/schema` linked so both it
// and its mirror run, compiled.
const compileDifferentialFixture = async (): Promise<{ root: string; payload: CompilePayload }> => {
  const root = await createFixture({
    'pvlconfig.json': configJson({}),
    'src/schemas/cases.ts': DIFFERENTIAL_FILE,
  });
  await linkSchemaPackage(root);
  return { root, payload: await compile({ cwd: root }) };
};

// A file asserting, for every case, that the compiled export's inferred
// Input and Output are identical to the interpreted one's.
const TYPE_CHECK_FILE = [
  "import type { InferInput, InferOutput } from '@pvl/schema';",
  "import type * as compiled from './.pvl/schemas/cases.ts';",
  "import type * as interpreted from './src/schemas/cases.ts';",
  '',
  'type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;',
  '',
  ...Object.keys(DIFFERENTIAL_CASES).flatMap((exportName) => [
    `export const ${exportName}Input: Equal<InferInput<typeof compiled.${exportName}>, InferInput<typeof interpreted.${exportName}>> = true;`,
    `export const ${exportName}Output: Equal<InferOutput<typeof compiled.${exportName}>, InferOutput<typeof interpreted.${exportName}>> = true;`,
  ]),
  '',
].join('\n');

describe('compile(): Compiled Schemas validate as the interpreted path does', () => {
  it('returns the same value, Issue messages and Issue paths for generated inputs', async () => {
    const { root, payload } = await compileDifferentialFixture();
    const interpreted = (await import(join(root, 'src/schemas/cases.ts'))) as CasesModule;
    const compiled = (await import(join(root, '.pvl/schemas/cases.ts'))) as CasesModule;

    expect(payload.diagnostics).toEqual([]);
    expect(await readFixtureFile(root, '.pvl/schemas/cases.ts')).not.toMatch(
      /pvl\.compile\((?!\))/,
    );
    for (const exportName of [...Object.keys(DIFFERENTIAL_CASES), 'interpretedParent']) {
      fc.assert(
        fc.property(fc.oneof(validatedValue, parentValue), (value) => {
          expect(describeResult(compiled[exportName]!.validate(value))).toStrictEqual(
            describeResult(interpreted[exportName]!.validate(value)),
          );
        }),
        { numRuns: 300 },
      );
    }
  });
});

describe('compile(): Compiled Schemas type as the interpreted path does', () => {
  it('emits code that typechecks strictly, inferring the Input and Output pvl.compile() does', async () => {
    const { root, payload } = await compileDifferentialFixture();
    const project = new Project({
      compilerOptions: {
        strict: true,
        noImplicitOverride: true,
        noUncheckedIndexedAccess: true,
        noEmit: true,
        allowImportingTsExtensions: true,
        module: ts.ModuleKind.ESNext,
        moduleResolution: ts.ModuleResolutionKind.Bundler,
        target: ts.ScriptTarget.ES2022,
      },
    });
    project.addSourceFileAtPath(join(root, '.pvl/schemas/cases.ts'));
    project.createSourceFile(join(root, 'types.ts'), TYPE_CHECK_FILE);

    expect(payload.diagnostics).toEqual([]);
    expect(
      project
        .getPreEmitDiagnostics()
        .map(
          (diagnostic) =>
            `${String(diagnostic.getLineNumber())}: ${ts.flattenDiagnosticMessageText(diagnostic.compilerObject.messageText, ' ')}`,
        ),
    ).toEqual([]);
  });
});
