import { chmod, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { compile, DIAGNOSTIC_CODE, SEVERITY } from '../src/index.js';
import { SCHEMA_FILE } from './consts.js';
import {
  configJson,
  createFixture,
  diagnosticCodes,
  expectFailure,
  readFixtureFile,
} from './helpers.js';

describe('compile(): writing the Destination File', () => {
  it('writes only the generated header to the configured destination', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'generated/schemas.ts' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(payload.written).toBe(true);
    expect(payload.destination).toBe(join(root, 'generated/schemas.ts'));
    expect(await readFixtureFile(root, 'generated/schemas.ts')).toMatchInlineSnapshot(`
      "// @generated by @pvl/schema-compiler. Do not edit: run \`pvl compile\` to regenerate.
      "
    `);
  });

  it('overwrites an existing Destination File', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'out.ts' }),
      'src/schemas/user.ts': SCHEMA_FILE,
      'out.ts': 'stale',
    });

    await compile({ cwd: root });

    expect(await readFixtureFile(root, 'out.ts')).toContain('@generated');
  });

  it('resolves the default destination under the anchor and writes nothing there yet', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toEqual([]);
    expect(payload.destination).toBe(join(root, 'node_modules/.pvl/compiled-schemas'));
    expect(payload.written).toBe(false);
    expect(await readFixtureFile(root, 'node_modules/.pvl/compiled-schemas/index.ts')).toBe(
      undefined,
    );
  });
});

describe('compile(): settings', () => {
  it('applies the defaults when the config sets nothing', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({}),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(payload.settings).toEqual({
      include: ['src/schemas/**/*.ts'],
      destination: undefined,
      withTypes: true,
      watch: false,
    });
  });

  it('reads every setting from the config file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({
        $schema: './node_modules/@pvl/schema-compiler/dist/json-schema.json',
        include: ['schemas/*.ts'],
        destination: 'out.ts',
        withTypes: false,
        watch: true,
      }),
      'schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expect(payload.settings).toEqual({
      include: ['schemas/*.ts'],
      destination: 'out.ts',
      withTypes: false,
      watch: true,
    });
  });

  it('lets an override win over the config file, setting by setting', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({
        include: ['schemas/*.ts'],
        destination: 'from-config.ts',
        withTypes: false,
      }),
      'schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({
      cwd: root,
      overrides: { destination: 'from-override.ts', withTypes: true },
    });

    expect(payload.settings).toEqual({
      include: ['schemas/*.ts'],
      destination: 'from-override.ts',
      withTypes: true,
      watch: false,
    });
    expect(await readFixtureFile(root, 'from-override.ts')).toContain('@generated');
    expect(await readFixtureFile(root, 'from-config.ts')).toBe(undefined);
  });

  it('runs with no config file when overrides are given, anchored at the working directory', async () => {
    const root = await createFixture({ 'src/schemas/user.ts': SCHEMA_FILE });

    const payload = await compile({ cwd: root, overrides: { destination: 'out.ts' } });

    expect(payload.diagnostics).toEqual([]);
    expect(payload.destination).toBe(join(root, 'out.ts'));
    expect(await readFixtureFile(root, 'out.ts')).toContain('@generated');
  });

  it('anchors relative paths at the config file, wherever it is run from', async () => {
    const files = {
      'apps/web/pvlconfig.json': configJson({ include: ['schemas/*.ts'], destination: 'out.ts' }),
      'apps/web/schemas/user.ts': SCHEMA_FILE,
    };
    const fromRepoRoot = await createFixture(files);
    const fromApp = await createFixture(files);

    const rootPayload = await compile({
      cwd: fromRepoRoot,
      configPath: 'apps/web/pvlconfig.json',
    });
    const appPayload = await compile({ cwd: join(fromApp, 'apps/web') });

    expect(rootPayload.diagnostics).toEqual([]);
    expect(appPayload.diagnostics).toEqual([]);
    expect(rootPayload.destination).toBe(join(fromRepoRoot, 'apps/web/out.ts'));
    expect(appPayload.destination).toBe(join(fromApp, 'apps/web/out.ts'));
    expect(await readFixtureFile(fromRepoRoot, 'apps/web/out.ts')).toBe(
      await readFixtureFile(fromApp, 'apps/web/out.ts'),
    );
  });

  it('never scans node_modules', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['**/*.ts'], destination: 'out/schemas.js' }),
      'src/user.ts': SCHEMA_FILE,
      'node_modules/dep/index.ts': 'console.log("side effect");\n',
    });

    const payload = await compile({ cwd: root });

    // `index.ts` exports nothing, so scanning it would have warned.
    expect(payload.diagnostics).toEqual([]);
  });
});

describe('compile(): diagnostics', () => {
  it('NO_CONFIG: no config file and no overrides', async () => {
    const root = await createFixture({ 'src/schemas/user.ts': SCHEMA_FILE });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [{ code: DIAGNOSTIC_CODE.NO_CONFIG }]);
  });

  it('CONFIG_UNREADABLE: an explicit config path that does not exist', async () => {
    const root = await createFixture({ 'src/schemas/user.ts': SCHEMA_FILE });

    const payload = await compile({ cwd: root, configPath: 'missing.json' });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.CONFIG_UNREADABLE, file: join(root, 'missing.json') },
    ]);
  });

  it('CONFIG_UNREADABLE: a config file that is not valid JSON', async () => {
    const root = await createFixture({
      'pvlconfig.json': '{ "destination": ',
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.CONFIG_UNREADABLE, file: join(root, 'pvlconfig.json') },
    ]);
  });

  it('INVALID_CONFIG: one diagnostic per failing setting, naming its path', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: 'src/**/*.ts', withTypes: 'yes' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    const file = join(root, 'pvlconfig.json');
    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.INVALID_CONFIG, file },
      { code: DIAGNOSTIC_CODE.INVALID_CONFIG, file },
    ]);
    expect(payload.diagnostics[0]?.message).toContain('include');
    expect(payload.diagnostics[1]?.message).toContain('withTypes');
  });

  it('INVALID_CONFIG: an unknown key, so a typo is reported', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destinaton: 'out.ts' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.INVALID_CONFIG, file: join(root, 'pvlconfig.json') },
    ]);
    expect(payload.diagnostics[0]?.message).toContain('destinaton');
    expect(await readFixtureFile(root, 'out.ts')).toBe(undefined);
  });

  it('INVALID_CONFIG: a config file that is not an object', async () => {
    const root = await createFixture({
      'pvlconfig.json': '[]',
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.INVALID_CONFIG, file: join(root, 'pvlconfig.json') },
    ]);
  });

  it('INVALID_CONFIG: an override of the wrong type, with no file', async () => {
    const root = await createFixture({ 'src/schemas/user.ts': SCHEMA_FILE });

    const payload = await compile({
      cwd: root,
      overrides: { destination: 42 as unknown as string },
    });

    expectFailure(payload, [{ code: DIAGNOSTIC_CODE.INVALID_CONFIG }]);
  });

  it('NO_INPUT_FILES: include matches no file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['schemas/*.ts'], destination: 'out.ts' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [{ code: DIAGNOSTIC_CODE.NO_INPUT_FILES }]);
    expect(await readFixtureFile(root, 'out.ts')).toBe(undefined);
  });

  it('NO_INPUT_FILES: include matches only directories', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['src/*'], destination: 'out.ts' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [{ code: DIAGNOSTIC_CODE.NO_INPUT_FILES }]);
  });

  it('DESTINATION_INSIDE_INCLUDE: include would match the Destination File', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: './src/schemas/compiled.ts' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      {
        code: DIAGNOSTIC_CODE.DESTINATION_INSIDE_INCLUDE,
        file: join(root, 'src/schemas/compiled.ts'),
      },
    ]);
    expect(await readFixtureFile(root, 'src/schemas/compiled.ts')).toBe(undefined);
  });

  it('DESTINATION_INSIDE_INCLUDE: also outside the anchor', async () => {
    const root = await createFixture({
      'app/pvlconfig.json': configJson({
        include: ['../shared/**/*.ts'],
        destination: '../shared/out.ts',
      }),
      'shared/user.ts': SCHEMA_FILE,
    });

    const payload = await compile({ cwd: join(root, 'app') });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.DESTINATION_INSIDE_INCLUDE, file: join(root, 'shared/out.ts') },
    ]);
  });

  it('DESTINATION_UNWRITABLE: the destination is an existing directory', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'out' }),
      'src/schemas/user.ts': SCHEMA_FILE,
      'out/keep.txt': '',
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.DESTINATION_UNWRITABLE, file: join(root, 'out') },
    ]);
  });

  it('DESTINATION_UNWRITABLE: a parent of the destination is a file', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'notes.txt/out.ts' }),
      'src/schemas/user.ts': SCHEMA_FILE,
      'notes.txt': '',
    });

    const payload = await compile({ cwd: root });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.DESTINATION_UNWRITABLE, file: join(root, 'notes.txt/out.ts') },
    ]);
    expect(await readFixtureFile(root, 'notes.txt')).toBe('');
  });

  it('DESTINATION_UNWRITABLE: the destination directory is read-only', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'locked/nested/out.ts' }),
      'src/schemas/user.ts': SCHEMA_FILE,
    });
    await mkdir(join(root, 'locked'));
    await chmod(join(root, 'locked'), 0o555);

    try {
      const payload = await compile({ cwd: root });

      expectFailure(payload, [
        {
          code: DIAGNOSTIC_CODE.DESTINATION_UNWRITABLE,
          file: join(root, 'locked/nested/out.ts'),
        },
      ]);
      expect(await readFixtureFile(root, 'locked/nested/out.ts')).toBe(undefined);
    } finally {
      await chmod(join(root, 'locked'), 0o755);
    }
  });

  it('FILE_EXPORTS_NOTHING: a warning that still writes', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'out.ts' }),
      'src/schemas/user.ts': SCHEMA_FILE,
      'src/schemas/setup.ts': 'console.log("side effect");\n',
    });

    const payload = await compile({ cwd: root });

    expect(payload.diagnostics).toStrictEqual([
      {
        code: DIAGNOSTIC_CODE.FILE_EXPORTS_NOTHING,
        severity: SEVERITY.WARNING,
        message: expect.any(String),
        file: join(root, 'src/schemas/setup.ts'),
      },
    ]);
    expect(payload.written).toBe(true);
    expect(await readFixtureFile(root, 'out.ts')).toContain('@generated');
  });

  it('strict: promotes a warning to an error, so nothing is written', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ destination: 'out.ts' }),
      'src/schemas/setup.ts': 'console.log("side effect");\n',
      'out.ts': 'previous output',
    });

    const payload = await compile({ cwd: root, strict: true });

    expectFailure(payload, [
      { code: DIAGNOSTIC_CODE.FILE_EXPORTS_NOTHING, file: join(root, 'src/schemas/setup.ts') },
    ]);
    expect(await readFixtureFile(root, 'out.ts')).toBe('previous output');
  });

  it('reports every error from one run together', async () => {
    const root = await createFixture({
      'pvlconfig.json': configJson({ include: ['src/**/*.ts'], destination: 'src/out.ts' }),
    });

    const payload = await compile({ cwd: root });

    expect(diagnosticCodes(payload)).toEqual([
      DIAGNOSTIC_CODE.DESTINATION_INSIDE_INCLUDE,
      DIAGNOSTIC_CODE.NO_INPUT_FILES,
    ]);
  });
});
